import test from 'node:test';
import assert from 'node:assert/strict';
import {createStore} from '../src/state.js';
import {createDemoCommands} from '../src/services.js';
import {canRateIndependent} from '../src/learning.js';
import {render as examPage} from '../src/pages/exam.js';
const setup=()=>{const memory=new Map();const storage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v)};const state=createStore(storage);return {state,commands:createDemoCommands(state),memory,storage};};
test('voice focus is frozen across later selection; save and schedule are separate',()=>{const {state,commands}=setup();commands.capture('ship');state.update(s=>s.focusWord='journey');commands.saveCaptured();const point=state.get().reviews.find(r=>r.wordId==='ship');assert.equal(point.status,'pending');assert.equal(point.when,null);commands.schedule(point.id);assert.equal(state.get().reviews.find(r=>r.id===point.id).when,'明天 19:30');});
test('undo one contribution preserves another and original historical review',()=>{const {state,commands}=setup();commands.capture('ship');const a=commands.saveCaptured();commands.capture('ship');const b=commands.saveCaptured();commands.undo(a.operationId);assert.equal(state.get().reviews.filter(r=>r.wordId==='ship').length,1);commands.undo(b.operationId);assert.equal(state.get().reviews.filter(r=>r.wordId==='ship').length,0);assert.equal(state.get().reviews[0].id,'seed-journey');});
test('undo does not erase already completed practice; completion is idempotent',()=>{const {state,commands}=setup();commands.capture('ship');const a=commands.saveCaptured();const point=state.get().reviews.find(r=>r.wordId==='ship');commands.finishReview(point.id);commands.finishReview(point.id);commands.undo(a.operationId);assert.equal(state.get().completed.length,1);assert.equal(state.get().reviews.find(r=>r.id===point.id).status,'done');});
test('reveal-only and hint paths cannot claim independent recall',()=>{assert.equal(canRateIndependent({result:null,hinted:false,revealed:true}),false);assert.equal(canRateIndependent({result:'self-recalled',hinted:true}),false);assert.equal(canRateIndependent({result:'self-recalled',hinted:false}),true);});
test('plan edits preserve practice history and survive browser reload',()=>{const {state,commands,storage}=setup();commands.complete('ship','词义','self-good');commands.plan(30,'managed');const restored=createStore(storage).get();assert.equal(restored.budget,30);assert.equal(restored.completed.length,1);assert.equal(restored.completed[0].result,'self-good');});
test('blocked or malformed storage degrades without preventing learning',()=>{const blocked=createStore({getItem:()=>{throw Error('blocked');},setItem:()=>{throw Error('blocked');}});assert.equal(blocked.get().budget,20);assert.equal(blocked.update(s=>s.budget=30).persisted,false);const bad=createStore({getItem:()=>JSON.stringify({schema:1,reviews:[null],completed:[]})});assert.equal(bad.get().reviews[0].wordId,'journey');});
test('exam conceals answers until separate publish step; restored text is escaped',()=>{const state={exam:{status:'active',answers:[]}};assert.ok(!examPage(state).includes('参考答案：'));state.exam.status='pending';assert.ok(!examPage(state).includes('参考答案：'));state.exam.status='graded';assert.ok(!examPage(state).includes('参考答案：'));state.exam.status='published';state.exam.answers=['<img src=x onerror=alert(1)>'];assert.ok(examPage(state).includes('&lt;img'));assert.ok(!examPage(state).includes('<img'));});

test('new contribution after completed practice creates a pending review without deleting history',()=>{const {state,commands}=setup();commands.capture('ship');commands.saveCaptured();const previous=state.get().reviews.find(r=>r.wordId==='ship');commands.finishReview(previous.id);commands.capture('ship');const next=commands.saveCaptured();assert.equal(state.get().reviews.filter(r=>r.wordId==='ship').length,2);assert.equal(state.get().reviews.filter(r=>r.wordId==='ship'&&r.status==='pending').length,1);commands.undo(next.operationId);assert.equal(state.get().reviews.find(r=>r.wordId==='ship').status,'done');assert.equal(state.get().completed.length,1);});
import {resolveReviewTarget} from '../src/agent-intent.js';
test('Agent clarifies multiple or unknown targets instead of guessing current focus',()=>{assert.equal(resolveReviewTarget('这个词明天练发音','ship').wordId,'ship');assert.equal(resolveReviewTarget('journey 明天练发音','ship').wordId,'journey');assert.ok(resolveReviewTarget('ship和journey明天练发音','ship').error);assert.ok(resolveReviewTarget('ship或apple明天练发音','ship').error);assert.ok(resolveReviewTarget('明天练发音','ship').error);});
