import {words,getWord} from '../content.js';
import {header,icon,go,escape} from '../ui.js';
export const coach={inCall:false};
export function render(state) {
 return `${header('你的英语教练','读懂进度，也帮你安排下一步')}<section class="avatar-stage"><span class="avatar-preview-label">数字人呈现占位</span><div class="avatar-illustration" aria-hidden="true"><svg viewBox="0 0 220 180"><path fill="#cadfd5" d="M20 180c3-48 36-69 90-69s85 22 90 69"/><path fill="#e9bd97" d="M93 103h34v28c-12 14-23 14-34 0"/><ellipse cx="110" cy="67" rx="44" ry="52" fill="#edc7a7"/><path fill="#263c3a" d="M64 73C41 9 89-5 112 5c47-6 51 30 42 62-4-28-19-26-27-44-15 19-40 17-51 31l-2 22"/><path d="M91 74h1m36 0h1" stroke="#33423c" stroke-width="5" stroke-linecap="round"/><path d="M103 91q9 8 18-1" fill="none" stroke="#9d6656" stroke-width="3" stroke-linecap="round"/><path fill="#416458" d="m86 124 24 24 24-24 17 56H70"/></svg></div><div class="call-controls"><button class="call-button ${coach.inCall?'calling':''}" data-action="call" aria-label="${coach.inCall?'结束模拟通话':'开始模拟通话'}" aria-pressed="${coach.inCall}">${icon(coach.inCall?'close':'mic',24)}</button><span>${coach.inCall?'模拟通话中 · 点击结束':'点击模拟通话'}</span></div></section>
 <div class="coach-context"><label for="focus-word">正在聊的词</label><select id="focus-word">${words.map(w=>`<option value="${w.id}" ${w.id===state.focusWord?'selected':''}>${w.word}</option>`).join('')}</select></div>
 <div class="chat"><div class="message coach-message"><small>拾语教练 · 模拟</small><p>今天想练什么？你可以说：<br>“这个词明天练发音。”</p><span>发音评测关闭，基础学习照常继续。</span></div>${state.messages.map(m=>`<div class="message ${m.type==='user'?'user-message':'coach-message'}"><p>${escape(m.text)}</p>${m.operationId?`<button class="text-button" data-action="undo" data-id="${escape(m.operationId)}" ${m.undone?'disabled':''}>${m.undone?'本次收录已撤销':'撤销本次收录'}</button>`:''}</div>`).join('')}</div>
 ${state.capture?`<div class="capture-preview"><span class="eyebrow">语音指令预览 · 对象已固定</span><h3>${getWord(state.capture.wordId).word} · 明天练发音</h3><p>之后切换正在聊的词，不会改变本次对象。</p><div><button class="primary compact" data-action="save-capture">加入演示复习点</button><button class="text-button" data-action="cancel-capture">取消</button></div></div>`:''}
 <div class="suggestions"><button data-action="capture-focus">${icon('mic',15)} 模拟：“这个词明天练发音”</button><button data-action="coach-progress">看看我的学习进度</button>${go('去计划安排 ↗','plan','suggestion-link')}</div><form id="coach-form" class="composer"><label class="sr-only" for="coach-input">给教练的文字指令</label><input id="coach-input" name="message" placeholder="输入，如 ship 明天练发音" autocomplete="off"><button class="send-button" aria-label="发送模拟指令">${icon('arrow',19)}</button></form><p class="small-note">语音为模拟，不录音；回复为预设演示，不调用模型。</p>`;
}
