import {examQuestions} from '../content.js';
import {header,icon,escape} from '../ui.js';
export function render(state) {
 const exam=state.exam;
 if(!exam)return `${header('给自己一次小测','阶段测试 · 先独立作答')}<div class="exam-hero"><div class="exam-emblem">${icon('plan',44)}</div><p class="eyebrow">A LITTLE CHECK-IN</p><h2>试着独立完成。<br>答案，交卷后再见。</h2><p>3 道样例题 · 词义与语境<br>可随时离开，浏览器保留未交卷作答。</p></div><div class="exam-rules"><p>① 考试中不揭晓答案、不即时纠错</p><p>② 交卷后先待评分，再模拟发布结果</p><p>③ 本次不含发音评分，也不是正式能力诊断</p></div><button class="primary full" data-action="exam-start">开始样例小测 ${icon('arrow',18)}</button>`;
 if(exam.status==='pending')return `${header('答卷已封存','演示状态 · 待评分','exam')}<div class="exam-hero"><div class="exam-emblem">${icon('check',44)}</div><h2>先收好你的答案。</h2><p>已交卷，暂不显示成绩。<br>下一步模拟评分结果发布。</p></div><button class="primary full" data-action="exam-grade">模拟完成评分</button><p class="small-note">不调用评分服务；仅按样例题的固定答案演示。</p>`;
 if(exam.status==='graded')return `${header('评分完成，等待发布','演示状态 · 未发布','home')}<div class="exam-hero"><div class="exam-emblem">${icon('check',44)}</div><h2>评分已准备好。</h2><p>发布后才会出现成绩和讲评。</p></div><button class="primary full" data-action="exam-publish">发布演示结果</button>`;
 if(exam.status==='published'){const score=examQuestions.filter((q,i)=>exam.answers[i]===q.answer).length;return `${header('这次尝试的回顾','样例小测 · 演示结果','home')}<div class="exam-score"><strong>${score}<span>/ 3</span></strong><p>本次客观正确题数，不代表学习能力评级。</p></div>${examQuestions.map((q,i)=>`<article class="exam-result"><small>QUESTION ${i+1} · ${exam.answers[i]===q.answer?'本题正确':'建议再练'}</small><h3>${q.prompt}</h3><p>你的答案：${escape(exam.answers[i]??'未作答')}</p><p class="correct-answer">参考答案：${q.answer}</p></article>`).join('')}<button class="secondary full" data-action="exam-reset">重新开始样例小测</button>`;}
 return `${header('独立作答','样例小测 · 离开后可继续','home')}<div class="exam-topline"><span>3 道题</span><span>已答 ${exam.answers.filter(Boolean).length} / 3</span></div><form id="exam-form">${examQuestions.map((q,i)=>`<fieldset class="exam-question"><legend><small>QUESTION ${i+1}</small><span>${q.prompt}</span></legend>${q.choices.map(c=>`<label><input type="radio" name="q${i}" value="${c}" ${exam.answers[i]===c?'checked':''}><span>${c}</span></label>`).join('')}</fieldset>`).join('')}<button class="primary full">交卷</button></form><p class="small-note">交卷后不能继续修改这份答卷。</p>`;
}
