import {icon,go,section} from '../ui.js';
import {getBook,getWord} from '../content.js';
import {dailyOverview} from '../study-services.js';
export function render(state) {
  const today=dailyOverview(state);
  const book=getBook(state.selectedBook);
  const total=today.newIds.length+today.due.length;
  const pending=state.reviews.filter(r=>r.status==='pending'&&!r.paused).length;
  const week=[0,0,0,0,0,0,state.completed.length];
  return `<header class="home-header"><div><p class="home-date">10 月 5 日，星期一</p><h1>今日学习</h1></div><button class="profile-button" data-route="profile" aria-label="我的学习设置">N</button></header>
  <section class="today-overview"><div class="today-overview-title"><span>${book.title}</span><button class="text-button" data-route="learning-settings">${state.learning.dailyLimit} 词 / 天 ${icon('setting',16)}</button></div><div class="today-progress"><strong>${today.done}</strong><span>演示练习次数</span><small>今天可执行 ${total} 项</small></div><div class="today-metrics"><button data-route="review"><span class="metric-caption"><i class="metric-dot review-dot"></i>优先复习</span><strong>${String(today.due.length).padStart(2,'0')}</strong><small>项已安排任务</small></button><button data-route="library"><span class="metric-caption"><i class="metric-dot new-dot"></i>可以新学</span><strong>${String(today.newIds.length).padStart(2,'0')}</strong><small>个所选新词</small></button></div>${go('开始学习 '+icon('arrow',18),'learn','primary full start-learning')}<div class="today-conditions"><span>${icon('clock',14)} ${state.budget} 分钟预算</span><button data-action="quiet">${icon(state.quiet?'muted':'audio',14)} ${state.quiet?'静音学习':'可以开口'}</button></div></section>
  <div class="quick-tools">${[['review','复习点','review'],['plan','学习计划','plan'],['exam','阶段测试','check'],['stats','学习统计','chart']].map(([route,label,i])=>`<button data-route="${route}"><span>${icon(i,22)}</span><small>${label}</small></button>`).join('')}</div>
  ${section('今日安排',go('查看计划 '+icon('arrow',14),'plan','text-button'))}<div class="path-list"><button data-route="review"><span class="path-icon">${icon('review')}</span><span><strong>先完成到期复习</strong><small>${today.due.length} 项今天已安排 · ${pending} 项等待安排</small></span>${icon('arrow',17)}</button><button data-route="library"><span class="path-icon">${icon('book')}</span><span><strong>${book.title}</strong><small>${today.newIds.slice(0,3).map(id=>getWord(id).word).join(' · ')||'当前无待新学任务，可调整学习范围'}</small></span>${icon('arrow',17)}</button><button data-route="coach"><span class="path-icon">${icon('coach')}</span><span><strong>AI 英语陪练</strong><small>按住说话 / 全屏数字人通话</small></span>${icon('arrow',17)}</button></div>
  ${section('本周的演示尝试',go('更多统计 ↗','stats','text-button'))}<section class="week-preview"><div class="week-chart">${week.map((n,i)=>`<button data-action="week-day" data-day="${i}" aria-label="查看周${['二','三','四','五','六','日','一'][i]}演示"><i style="height:${Math.min(44,Math.max(n*4,2))}px"></i><span>${['二','三','四','五','六','日','一'][i]}</span></button>`).join('')}</div><div class="week-caption"><strong>${state.completed.length}<small>次尝试</small></strong><p>记录每一次练习<br>不把单次答对当成掌握</p></div></section><div class="workload-notice"><span>${icon('info',18)}</span><p>浏览器中的练习、收录和计划均为交互演示；真实学习调度与评分还未接入。</p></div>`;
}
