import {words,displayType} from '../content.js';
import {header,icon,escape,go} from '../ui.js';
export const session={index:0,mode:'recall',direction:'en-cn',revealed:false,hinted:false,result:null,answer:'',audioPlayed:false,readText:false,generation:0,focus:false,wordTab:'meaning',queue:[]};
export function resetQuestion() {
  session.generation++;session.revealed=false;session.hinted=false;session.result=null;session.answer='';session.audioPlayed=false;session.readText=false;session.wordTab='meaning';
}
export function render(state) {
  const w=words[session.index];const revealing=session.revealed;const fromReview=session.reviewId;
  const current=session.queue.indexOf(w.id)+1;
  return `<header class="focus-learning-header"><button class="icon-button" data-route="${fromReview?'review':'home'}" aria-label="退出学习">${icon('close',21)}</button><span>${fromReview?'专项复习':`${current||1} / ${session.queue.length||1}`}<small>${session.mode==='recall'?(session.direction==='cn-en'?'中 → 英':'英 → 中'):session.mode==='spell'?'拼写':'听辨'}</small></span><div><button class="icon-button" data-action="learn-focus" aria-label="${session.focus?'退出专注全屏':'进入专注全屏'}">${icon('expand',19)}</button><button class="icon-button" data-action="learn-familiar" aria-label="将本词标记为熟知">${icon('check',21)}</button></div></header>
  <div class="focus-learning-tools"><div class="learning-direction"><button data-action="learn-direction" data-direction="en-cn" class="${session.direction==='en-cn'?'selected':''}">英 → 中</button><button data-action="learn-direction" data-direction="cn-en" class="${session.direction==='cn-en'?'selected':''}">中 → 英</button></div><div class="activity-tabs compact-tabs">${[['recall','回忆'],['spell','拼写'],['listen','听辨']].map(([mode,label])=>`<button data-action="learn-mode" data-mode="${mode}" class="${session.mode===mode?'selected':''}" aria-pressed="${session.mode===mode}">${label}</button>`).join('')}</div></div>
  <section class="focus-word-area ${revealing?'revealed':''}"><p class="eyebrow">${session.mode==='recall'?(session.direction==='cn-en'?'MEANING → ENGLISH':'ENGLISH → MEANING'):session.mode==='spell'?'ACTIVE SPELLING':'LISTEN & RECALL'}</p>
  ${session.mode==='recall'?`<h1 class="focus-word ${session.direction==='cn-en'?'meaning-word':''}">${escape(session.direction==='cn-en'?w.meaning:w.word)}</h1>${session.direction==='en-cn'?`<div class="ipa">${w.ipa?escape(w.ipa):'音标待补充'}<button class="icon-button audio" data-action="speak" data-text="${escape(w.word)}" aria-label="播放 ${escape(w.word)} 示范发音">${icon('audio',20)}</button></div>`:`<p class="muted">先在心里说出英文</p><button class="icon-button audio" data-action="speak" data-text="${escape(w.word)}" aria-label="听目标词发音（提示）">${icon('audio',20)}</button>`}${!revealing?`<button class="tap-to-reveal" data-action="learn-reveal">先回忆，再点这里查看${session.direction==='cn-en'?'英文':'释义'}<span>不把揭晓后的想起算成独立回忆</span></button>`:''}`:session.mode==='spell'?`<h2 class="meaning">${escape(w.meaning)}</h2><p class="muted">从词义找回它的英文拼写</p><form id="spell-form"><label class="sr-only" for="spelling">英文拼写</label><input id="spelling" name="answer" autocomplete="off" spellcheck="false" placeholder="你的英文答案…" value="${escape(session.answer)}" ${revealing?'disabled':''}><button class="primary" ${revealing?'disabled':''}>提交拼写</button></form>`:`<button class="listen-circle" data-action="speak" data-text="${escape(w.example||w.word)}" aria-label="播放听辨示范">${icon('audio',36)}</button><p class="muted">${w.example?'句子里的目标词是什么意思？':'听到的这个词是什么意思？'}</p><div class="choices">${[w.meaning,'城市；街道','回答；回应'].map((x,i)=>`<button data-action="listen-answer" data-choice="${i}" ${revealing?'disabled':''}>${String.fromCharCode(65+i)} <span>${escape(x)}</span></button>`).join('')}</div><details class="transcript"><summary>听不到？阅读文本继续</summary><p>${escape(w.example||w.word)}</p></details>`}
  ${session.hinted&&!revealing?`<div class="hint">提示：${w.hint?escape(w.hint):'暂无额外提示，查看答案后按补练记录'}</div>`:''}
  ${revealing?`<div class="answer-reveal"><span class="answer-label">${session.mode==='recall'?(session.result==='self-recalled'?'核对刚才想起的答案':'先对照答案补练'):session.result==='correct'?'本次答对，不等于已掌握':'对照答案，再练一次'}</span><h3>${session.mode==='spell'||session.direction==='cn-en'?escape(w.word):`<span>${escape(displayType(w))}</span> ${escape(w.meaning)}`}</h3><div class="word-detail-tabs">${[['meaning','词义'],['usage','例句'],['notes','笔记']].map(([tab,label])=>`<button data-action="word-detail-tab" data-tab="${tab}" class="${session.wordTab===tab?'selected':''}">${label}</button>`).join('')}</div>${session.wordTab==='meaning'?`<div class="definition-list"><p>${escape(displayType(w))} ${escape(w.meaning).replace(/\n/g,'<br>')}</p>${w.definition?`<details><summary>英文释义</summary><p>${escape(w.definition).replace(/\n/g,'<br>')}</p></details>`:''}</div><div class="word-context-label">释义：${escape(w.sourceLabel??'界面示例')}</div>`:session.wordTab==='usage'?`${w.example?`<p class="usage-sentence">${escape(w.example).replace(escape(w.word),`<strong>${escape(w.word)}</strong>`)}</p>`:'<p class="muted">暂无例句，可添加个人笔记。</p>'}${w.translation?`<p class="muted">${escape(w.translation)}</p>`:''}${w.example?`<p class="word-context-label">例句：${escape(w.exampleSource||'界面示例')}</p><button class="text-button" data-action="speak" data-text="${escape(w.example)}">${icon('audio',17)} 听例句</button>`:''}`:`<form id="word-note-form"><label class="sr-only" for="word-note">本词笔记</label><textarea id="word-note" name="note" rows="3" maxlength="500" placeholder="写下你的联想或想用的场景…">${escape(state.notes?.[w.id]??'')}</textarea><button class="secondary full">保存演示笔记</button></form>`}<p class="feedback-note">${session.hinted?'本次使用提示，记录为补练。':session.mode==='recall'?(session.result==='self-recalled'?'揭晓前已声明想起，请按核对结果自评。':'尚未独立回忆，补练之后再确认。'):'仅记录本次练习，不声称已掌握。'}</p></div>`:''}</section>
  <div class="learning-bottom">${!revealing&&session.mode==='recall'?`<div class="recall-primary-actions"><button class="secondary" data-action="learn-reveal">没想起，看看答案</button><button class="primary" data-action="recall-claimed" ${session.hinted?'disabled':''}>我已想起，核对</button></div><button class="text-button hint-trigger" data-action="learn-hint" ${w.hint?'':'disabled'}>${w.hint?'给我一点提示':'暂无额外提示'}</button>`:''}${revealing&&session.mode==='recall'?`<div class="ratings"><button data-action="learn-rate" data-rating="again">${session.hinted?'借提示想起':'记错了'}<small>补练</small></button><button data-action="learn-rate" data-rating="hard" ${session.hinted||session.result!=='self-recalled'?'disabled':''}>吃力但答对<small>独立回忆</small></button><button data-action="learn-rate" data-rating="good" ${session.hinted||session.result!=='self-recalled'?'disabled':''}>轻松答对<small>独立回忆</small></button><button data-action="learn-rate" data-rating="forgot">忘记<small>没想起来</small></button></div>`:''}${revealing&&session.mode!=='recall'?go('记录这次练习，继续 '+icon('arrow',18),'','primary full','data-action="learn-continue"'):''}<div class="learning-utilities"><button data-action="word-favorite" data-id="${escape(w.id)}">${icon('star',17)} ${state.favorites.includes(w.id)?'已收藏':'收藏'}</button><button data-action="capture-current">${icon('mic',17)} 明天练发音</button><button data-action="learn-next">跳过 ${icon('arrow',16)}</button></div><p class="small-note">只记录演示尝试 · 发音未自动评测</p></div>`;
}
