import {getWord,words} from '../content.js';
import {header,icon,escape,go} from '../ui.js';
export const session={index:0,mode:'recall',revealed:false,hinted:false,result:null,answer:'',audioPlayed:false,readText:false,generation:0};
export function resetQuestion() {session.generation++;session.revealed=false;session.hinted=false;session.result=null;session.answer='';session.audioPlayed=false;session.readText=false;}
export function render(state) {
 const w=words[session.index];const revealing=session.revealed;const fromReview=session.reviewId;
 return `${header(fromReview?'专项复习':'今日学习',`${session.index+1} / 3 · ${w.topic}`,fromReview?'review':'home')}<div class="activity-tabs" role="group" aria-label="练习类型">${[['recall','主动回忆'],['spell','拼写'],['listen','听辨']].map(([mode,label])=>`<button data-action="learn-mode" data-mode="${mode}" class="${session.mode===mode?'selected':''}" aria-pressed="${session.mode===mode}">${label}</button>`).join('')}</div>
 <div class="learning-topline"><span>${session.mode==='recall'?'先回忆，再揭晓':session.mode==='spell'?'从词义，找回单词':'先听完整，再选择'}</span><button class="text-button" data-action="learn-next">换一个词</button></div>
 <section class="word-card"><p class="eyebrow">${session.mode==='recall'?'ENGLISH → MEANING':session.mode==='spell'?'MEANING → SPELLING':'LISTEN → MEANING'}</p>
 ${session.mode==='recall'?`<h2 class="word">${w.word}</h2><div class="ipa">${w.ipa}<button class="icon-button audio" data-action="speak" data-text="${escape(w.word)}" aria-label="播放 ${w.word} 示范发音">${icon('audio',20)}</button></div><p class="recall-question">你能想起它的意思吗？</p>${!revealing?`<button class="primary full" data-action="recall-claimed" ${session.hinted?'disabled':''}>我已想起，核对答案</button>`:''}`:session.mode==='spell'?`<h2 class="meaning">${w.meaning}</h2><p class="muted">写下对应的英文单词</p><form id="spell-form"><label class="sr-only" for="spelling">英文拼写</label><input id="spelling" name="answer" autocomplete="off" spellcheck="false" placeholder="在这里输入英文…" value="${escape(session.answer)}" ${revealing?'disabled':''}><button class="primary" ${revealing?'disabled':''}>提交拼写</button></form>`:`<button class="listen-circle" data-action="speak" data-text="${escape(w.example)}" aria-label="播放听辨例句">${icon('audio',36)}</button><p class="muted">句子里的目标词是什么意思？</p><div class="choices">${[w.meaning,'城市；街道','回答；回应'].map((x,i)=>`<button data-action="listen-answer" data-choice="${i}" ${revealing?'disabled':''}>${String.fromCharCode(65+i)} <span>${x}</span></button>`).join('')}</div><details class="transcript"><summary>听不到？阅读文本继续</summary><p>${w.example}</p></details>`}
 ${session.hinted&&!revealing?`<div class="hint">提示：${w.hint}</div>`:''}
 ${revealing?`<div class="answer-reveal"><span class="answer-label">${session.mode==='recall'?(session.result==='self-recalled'?'核对刚才想起的答案':'参考答案'):session.result==='correct'?'这次答对了':'对照答案，再练一次'}</span>${session.mode==='recall'?`<h3><span>${w.type}</span> ${w.meaning}</h3>`:`<h3>${w.word} <small>${w.ipa}</small></h3>`}<p>${w.example}</p><p class="muted">${w.translation}</p><p class="feedback-note">${session.hinted?'本次使用了提示，记为补练。':session.mode==='recall'?(session.result==='self-recalled'?'你在揭晓前表示已想起，请按核对结果自评。':'尚未独立答对，先对照答案补练。'):'下次独立复习再确认，不计为已掌握。'}</p></div>`:''}</section>
 ${!revealing&&session.mode==='recall'?`<div class="learn-actions"><button class="secondary" data-action="learn-hint">给我一点提示</button><button class="primary" data-action="learn-reveal">没想起，看看答案</button></div><p class="small-note">先在心里说出答案，再揭晓。</p>`:''}
 ${revealing&&session.mode==='recall'?`<div class="ratings"><button data-action="learn-rate" data-rating="again">${session.hinted?'借提示才想起':'没想起来'}<small>再练一遍</small></button><button data-action="learn-rate" data-rating="hard" ${session.hinted||session.result!=='self-recalled'?'disabled':''}>吃力但答对<small>独立回忆</small></button><button data-action="learn-rate" data-rating="good" ${session.hinted||session.result!=='self-recalled'?'disabled':''}>轻松答对<small>独立回忆</small></button></div>`:''}
 ${revealing&&session.mode!=='recall'?go('记录这次练习，继续 '+icon('arrow',18),'','primary full','data-action="learn-continue"'):''}
 <button class="review-shortcut" data-action="capture-current">${icon('mic',18)} 模拟语音：这个词明天练发音 ${icon('arrow',16)}</button><p class="small-note">示范朗读来自浏览器；发音未自动评测。<br>内容：手工样例词条 v1</p>`;
}
