import {header,icon,escape,section,go} from '../ui.js';
import {getWord} from '../content.js';
import {dailyOverview} from '../study-services.js';
export const planState={day:0,tab:'schedule'};
export function render(state) {
  const pending=state.reviews.filter(r=>r.status==='pending'&&!r.paused);
  const scheduled=state.reviews.filter(r=>r.status==='planned'&&!r.paused);
  const today=dailyOverview(state);
  const shown=scheduled.filter(r=>planState.day===0?r.when?.startsWith('今天'):planState.day===1?r.when?.startsWith('明天'):false);
  return `${header('安排你的学习节奏','日常英语 · 可修改，不抹除旧记录')}<section class="goal-banner"><div class="goal-banner-top"><p class="eyebrow">YOUR NORTH STAR</p><span>${state.mode==='manual'?'手动计划':state.mode==='assisted'?'教练辅助':'教练托管'}</span></div><h2>${escape(state.goal??'在日常场景里，\n自信地说出来。').replace(/\n/g,'<br>')}</h2><div class="plan-key-values"><div><strong>${state.budget}<small>分钟 / 天</small></strong></div><div><strong>${state.learning.dailyLimit}<small>词 / 天上限</small></strong></div></div></section>
  <div class="statistics-tabs plan-tabs"><button data-action="plan-tab" data-tab="schedule" class="${planState.tab==='schedule'?'selected':''}">本周安排</button><button data-action="plan-tab" data-tab="goal" class="${planState.tab==='goal'?'selected':''}">目标与预算</button></div>
  ${planState.tab==='schedule'?`<div class="plan-week-strip">${['一','二','三','四','五','六','日'].map((day,i)=>`<button data-action="plan-day" data-day="${i}" aria-pressed="${planState.day===i}" class="${planState.day===i?'selected':''}"><small>${day}</small><strong>${5+i}</strong><i></i></button>`).join('')}</div>${section(`${planState.day===0?'今天':planState.day===1?'明天':'10 月 '+(5+planState.day)+' 日'}的安排`,go('调整学习量 ↗','learning-settings','text-button'))}<div class="plan-task-summary"><span>${planState.day===0?today.due.length:shown.length} 项复习</span><span>${planState.day===0?today.newIds.length:0} 个新词</span><span>${state.quiet?'静音条件':'可以开口'}</span></div><div class="timeline">${planState.day===0?`<div class="timeline-step"><span class="timeline-dot"></span><div><small>今日样例队列</small><h3>独立回忆 → 新词 → 检查反馈</h3><p>优先 ${today.due.length} 项复习，随后学习 ${today.newIds.length} 个可执行新词。</p>${go('开始今日学习','learn','text-button')}</div></div>`:''}${shown.map(r=>`<div class="timeline-step"><span class="timeline-dot pale"></span><div><small>${escape(r.when)}</small><h3>${escape(getWord(r.wordId).word)} · ${escape(r.skill)}练习</h3><p>${r.skill==='发音'?'示范、跟读、自听 · 未自动评测':'独立回忆，再对照答案'}</p><button class="text-button" data-action="review-pause" data-id="${escape(r.id)}">暂时暂停</button></div></div>`).join('')}${planState.day>0&&!shown.length?'<div class="empty-state"><h3>这一天，先留一点空间。</h3><p>没有已安排的样例任务。<br>加入复习点后，可以确认明日时段。</p></div>':''}</div>
  ${pending.length?`${section('已加入，等待安排',`<span class="counter">${pending.length}</span>`)}${pending.map(r=>`<article class="pending-row"><div><strong>${escape(getWord(r.wordId).word)} · ${escape(r.skill)}</strong><p>指定明天练 · 建议 19:30，3 分钟</p></div><button class="primary compact" data-action="schedule" data-id="${escape(r.id)}">确认安排</button></article>`).join('')}`:'<div class="plan-all-set">'+icon('check',18)+' 当前没有等待安排的复习点</div>'}<div class="plan-explanation">${icon('bolt',18)}<p>计划根据预算收敛，历史仍保留。<br><span>本页展示明确安排与样例任务，不运行真实后台调度或通知。</span></p></div>`:
  `<form id="plan-form"><section class="settings-block"><label class="field-label" for="plan-goal">我的学习目标</label><textarea id="plan-goal" name="goal" rows="2" maxlength="100">${escape(state.goal??'在日常场景里，自信地说出来。')}</textarea></section><fieldset><legend>每天可用时间</legend><div class="budget-options">${[10,20,30,45].map(n=>`<label><input type="radio" name="budget" value="${n}" ${state.budget===n?'checked':''}><span>${n}<small>分钟</small></span></label>`).join('')}</div></fieldset><label class="field-label" for="plan-mode">计划方式</label><select id="plan-mode" name="mode"><option value="manual" ${state.mode==='manual'?'selected':''}>手动计划 · 我来决定</option><option value="assisted" ${state.mode==='assisted'?'selected':''}>教练辅助 · 确认后安排</option><option value="managed" ${state.mode==='managed'?'selected':''}>教练托管 · 在我的预算内调整</option></select><p class="small-note left">托管不擅自改变目标；暂停不会清掉学习历史。</p><button class="primary full">保存目标与预算</button></form>${state.mode==='managed'?'<button class="secondary full" data-action="pause-management">暂停托管，改为手动</button>':''}<section class="science-explanation"><h3>上限不是必须完成的压力。</h3><p>每天复习与新学的总量可以缩减。切换目标或词书仍保留已发生的练习；未来真实调度服务会基于证据给出可行建议。</p></section>`}`;
}
