import {header,section,icon,go} from '../ui.js';
import {getBook} from '../content.js';
export function render(state) {
  return `${header('我的学习','让努力有记录，让设置有选择')}<div class="profile-heading"><span class="large-profile">N</span><div><h2>Namson</h2><p>日常英语学习者 · ${getBook(state.selectedBook).title}</p></div><span class="profile-edition">PREVIEW</span></div><div class="profile-metrics"><div><strong>${state.completed.length}</strong><span>演示练习次数</span></div><div><strong>${state.selectedWords.length}</strong><span>已选单词</span></div><div><strong>${state.reviews.length}</strong><span>复习点</span></div></div>
  <div class="profile-achievement"><span>${icon('bolt',25)}</span><div><h3>学习量由你决定</h3><p>复习、新词与学习时长可以独立调整。</p></div></div>
  ${section('学习管理')}<div class="settings-list">${[['library','book','词书与已选词',getBook(state.selectedBook).title],['learning-settings','arrow','学习量与记忆方向',state.learning.dailyLimit+' 词/天'],['review','review','我的复习点',state.reviews.filter(r=>r.status!=='done').length+' 项'],['plan','plan','学习计划',state.budget+' 分钟'],['stats','chart','学习统计','三类统计'],['exam','check','考试与历史成绩','阶段小测']].map(([route,i,label,note])=>`<button class="settings-row detailed" data-route="${route}"><span class="setting-icon">${icon(i,20)}</span><span>${label}<small>${note}</small></span>${icon('arrow',17)}</button>`).join('')}</div>
  ${section('偏好与数据')}<div class="settings-list"><button class="settings-row detailed" data-route="settings"><span class="setting-icon">${icon('setting',20)}</span><span>语音与界面设置<small>ASR / 声音 / 深色界面 / 提醒</small></span>${icon('arrow',17)}</button><button class="settings-row detailed" data-action="export"><span class="setting-icon">${icon('review',20)}</span><span>查看浏览器演示数据<small>只在此浏览器，不与云端同步</small></span>${icon('arrow',17)}</button></div>
  <details id="data-preview"><summary>演示保存与恢复说明</summary><p class="muted">浏览器 localStorage 保存本次交互记录。切换词书或设置保留旧记录；清除数据只影响本演示。存储不可用时会明确提示。</p><pre id="data-json">点击“查看浏览器演示数据”查看当前状态。</pre></details><button class="secondary full reset-data" data-action="reset-preview">重置全部演示数据</button><p class="small-note">拾语 · 网页界面预览 v0.2<br>学习服务与发音评测还未接入。</p>`;
}
