import {header,icon,go,section} from '../ui.js';
export function render(state) {
  const settings=state.settings;
  const statuses={ready:'模拟就绪',pending:'模拟未下载',failed:'模拟失败',loading:'模拟准备中'};
  return `${header('语音与界面设置','增强功能，可以按需开关','profile')}<section class="settings-block"><div class="settings-block-title"><span>${icon('mic',20)}</span><h2>语音识别</h2></div><div class="radio-tiles">${[['local','本地语音识别','设备端模型 · 当前仅模拟选择'],['cloud','云端识别','由未来配置的服务处理'],['text','只用文字','不需要麦克风和识别模型']].map(([value,title,note])=>`<label><input type="radio" name="asr-engine" value="${value}" ${settings.asr===value?'checked':''}><span><strong>${title}</strong><small>${note}</small></span>${icon('check',18)}</label>`).join('')}</div></section>
  <section class="settings-block ${settings.asr==='local'?'':'muted-model-block'}"><div class="section-heading"><h2>本地识别模型</h2><span class="sample-data-pill">状态模拟</span></div>${[['fast','Fast','轻快','响应优先，适合短指令'],['balanced','Balanced','均衡','速度与识别能力的默认选择'],['accurate','Accurate','精确','更高资源预算的选择']].map(([id,name,label,note])=>`<article class="asr-model ${settings.asrModel===id?'selected':''}"><button class="asr-model-select" data-action="asr-model" data-id="${id}" ${settings.asr!=='local'?'disabled':''}><span class="model-choice-dot" aria-hidden="true"></span><div><h3>${name} <small>${label}</small>${id==='balanced'?'<em>推荐</em>':''}</h3><p>${note}</p></div></button><div class="model-bottom"><span class="model-status ${state.modelStates[id]}">${statuses[state.modelStates[id]]}</span>${state.modelStates[id]==='ready'?'<span>不代表真实安装</span>':`<button class="text-button" data-action="simulate-model" data-id="${id}" ${state.modelStates[id]==='loading'?'disabled':''}>${state.modelStates[id]==='failed'?'模拟重试':'模拟准备'}</button>`}</div></article>`).join('')}<p class="small-note left">这些是界面状态，不下载模型、不占用模型磁盘。ASR 只负责识别文字，不是发音评分。</p></section>
  <section class="settings-block"><h2>示范声音</h2><div class="settings-inline"><label for="voice-accent">示范口音</label><select id="voice-accent"><option value="us" ${settings.voice==='us'?'selected':''}>美式 English (US)</option><option value="uk" ${settings.voice==='uk'?'selected':''}>英式 English (UK)</option></select></div><div class="settings-inline"><label for="speech-rate">朗读速度</label><select id="speech-rate">${[0.7,0.85,1,1.15].map(rate=>`<option value="${rate}" ${settings.rate===rate?'selected':''}>${rate}×</option>`).join('')}</select></div><button class="secondary full" data-action="speak" data-text="Small steps make a lasting difference.">${icon('audio',18)} 试听浏览器朗读</button><button class="quiet-row" data-action="quiet" aria-pressed="${state.quiet}"><span>静音学习</span><span class="toggle ${state.quiet?'on':''}" aria-hidden="true"></span></button></section>
  <section class="settings-block"><div class="setting-description"><div><h3>发音评测 SOE</h3><span class="disabled-pill">默认关闭</span></div><p>尚未配置，不影响学习、对话界面或加入发音复习。跟读、自听可继续使用；不会产生自动分数。</p></div></section>
  <section class="settings-block"><h2>显示与提醒</h2><button class="quiet-row" data-action="theme-toggle" aria-pressed="${settings.theme==='dark'}"><span>深色界面</span><span class="toggle ${settings.theme==='dark'?'on':''}" aria-hidden="true"></span></button><button class="quiet-row" data-action="reminder-toggle" aria-pressed="${settings.reminder}"><span>学习提醒 <small>演示 ${settings.reminderTime}</small></span><span class="toggle ${settings.reminder?'on':''}" aria-hidden="true"></span></button><p class="small-note left">提醒仅保存界面偏好，不建立系统通知；通话页显示双语字幕。</p></section>`;
}
