import {header,icon,go,escape} from '../ui.js';
import {statisticsQuery} from '../statistics.js';
export const statsState={tab:'forget',period:'week',source:'sample',selected:3,visible:{first:true,second:true,third:true,new:true,review:true,retention:true}};
export function render(state) {
  const data=statisticsQuery(state,statsState);
  const selected=Math.min(statsState.selected,data.labels.length-1);
  const series=data.series.filter(s=>statsState.visible[s.id]);
  const length=data.labels.length;
  const x=i=>28+i*(280/(length-1));const y=v=>177-v/data.max*137;
  const path=s=>s.values.map((v,i)=>`${i?'L':'M'} ${x(i)} ${y(v)}`).join(' ');
  const isBar=statsState.tab!=='forget';
  return `${header('看见学习的变化','图表为演示，证据才是进步的依据')}<div class="statistics-tabs" role="group" aria-label="统计页面">${[['forget','遗忘曲线'],['activity','学习情况'],['retention','记忆持久度']].map(([tab,label])=>`<button data-action="stats-tab" data-tab="${tab}" class="${statsState.tab===tab?'selected':''}" aria-pressed="${statsState.tab===tab}">${label}</button>`).join('')}</div>
  <div class="statistics-title"><p class="eyebrow">${statsState.tab==='forget'?'MEMORY, OVER TIME':statsState.tab==='activity'?'YOUR LEARNING RHYTHM':'A LONGER MEMORY'}</p><h2>${statsState.tab==='forget'?'复习，让记忆慢慢走远。':statsState.tab==='activity'?'每天的努力，都值得看见。':'从短暂想起，到更久记得。'}</h2><span class="sample-data-pill">${statsState.tab==='activity'&&statsState.source==='actual'?'浏览器演示记录':'示例数据 · 待真实数据'}</span></div>
  ${statsState.tab==='activity'?`<div class="stats-controls"><div class="segment-control">${[['day','日'],['week','周'],['month','月']].map(([period,label])=>`<button data-action="stats-period" data-period="${period}" class="${statsState.period===period?'selected':''}">${label}</button>`).join('')}</div><select id="stats-source" aria-label="图表数据来源"><option value="sample" ${statsState.source==='sample'?'selected':''}>示例趋势</option><option value="actual" ${statsState.source==='actual'?'selected':''}>本浏览器练习</option></select></div>`:''}
  <section class="statistics-chart"><p class="chart-unit">${data.unit}</p><div class="chart-canvas"><svg viewBox="0 0 336 212" role="img" aria-label="${escape(data.unit)}，可用下方日期按钮查看具体数值">${[0,.25,.5,.75,1].map(r=>`<line x1="28" y1="${y(data.max*r)}" x2="310" y2="${y(data.max*r)}" stroke="var(--line)" stroke-dasharray="3 5"/><text x="20" y="${y(data.max*r)+3}" text-anchor="end" class="chart-axis">${Math.round(data.max*r)}</text>`).join('')}${isBar?series.map((s,j)=>s.values.map((v,i)=>`<rect x="${x(i)-9+(j*10)}" y="${y(v)}" width="${series.length>1?8:16}" height="${177-y(v)}" rx="2" fill="${s.color}" opacity="${i===selected?1:.65}"/>`).join('')).join(''):series.map(s=>`<path d="${path(s)}" fill="none" stroke="${s.color}" stroke-width="2.5"/>${s.values.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="${i===selected?4:2.5}" fill="${s.color}"/>`).join('')}`).join('')}<line x1="${x(selected)}" y1="30" x2="${x(selected)}" y2="185" stroke="var(--muted)" opacity=".3"/>${data.labels.map((label,i)=>`<text x="${x(i)}" y="204" text-anchor="middle" class="chart-axis">${label}</text>`).join('')}</svg></div><div class="chart-point-buttons" aria-label="选择图表日期或间隔">${data.labels.map((label,i)=>`<button data-action="stats-point" data-index="${i}" aria-pressed="${selected===i}" class="${selected===i?'selected':''}" aria-label="查看${label}">${label}</button>`).join('')}</div><div class="chart-legend">${data.series.map(s=>`<button data-action="stats-series" data-series="${s.id}" aria-pressed="${statsState.visible[s.id]}" class="${statsState.visible[s.id]?'':'muted-series'}"><i style="background:${s.color}"></i>${s.label}${statsState.visible[s.id]?icon('check',13):''}</button>`).join('')}</div></section>
  <section class="chart-selected-detail"><span>${data.labels[selected]} · ${statsState.tab==='forget'?'复习后间隔':statsState.tab==='activity'?'查看这段学习':'持久度区间'}</span><div>${series.length?series.map(s=>`<p><i style="background:${s.color}"></i>${s.label}<strong>${s.values[selected]}<small>${statsState.tab==='forget'?'%':statsState.tab==='retention'?'词':statsState.source==='actual'&&statsState.tab==='activity'?'次':'项'}</small></strong></p>`).join(''):'<p class="muted">点击图例，选择要看的数据。</p>'}</div></section>
  <div class="statistics-evidence"><span>${icon('info',19)}</span><p>${data.notice}</p></div>
  ${statsState.tab==='activity'?`<div class="stats-bottom-metrics"><div><strong>${state.completed.length}</strong><span>实际演示尝试</span></div><div><strong>${new Set(state.completed.map(c=>c.wordId)).size}</strong><span>涉及单词</span></div><div><strong>${state.reviews.filter(r=>r.status==='done').length}</strong><span>演示复习完成</span></div></div>`:`<section class="science-explanation"><h3>${statsState.tab==='forget'?'比起一口气重复，隔一段时间再回忆。':'同一个词，不同技能要分别观察。'}</h3><p>${statsState.tab==='forget'?'先自己回想，再看答案。单次答对只是一次证据；后续独立复习与间隔测试，才能看见持续变化。':'词义、拼写、听辨和发音的表现可以不同。没有发音评测时，我们保留“未自动评测”，不会造出分数。'}</p>${go('回到今天的练习 ↗','home','text-button')}</section>`}`;
}
